name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    steps:
    - uses: actions/checkout@v3
    - run:
        cd server
        npm i
        cd ..
        cd client
        npm i
        npm run build
        
        