# name: Node.js CI

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   build:
#     runs-on: self-hosted
#     container: node:16
#     steps:
#     - uses: actions/checkout@v3
#     - run:
#         cd server
#         npm i
#         cd ..
#         cd client
#         npm i
#         npm run build
        
        



        name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    container: node:16
    steps:
    - uses: actions/checkout@v2
    - run:
        cd server
        npm i
        cd ..
        cd client
        npm i
        npm run build
        
        